name             'chef_worldping_api'
maintainer       'Raintank, Inc.'
maintainer_email 'cookbooks@raintank.io'
license          'Apache 2.0'
description      'Installs/Configures chef_worldping_api'
long_description 'Installs/Configures chef_worldping_api'
version          '0.1.2'

depends 'chef_base', '~> 0.1.9'
depends 'logrotate', '~> 1.9.1'
depends 'packagecloud', '~> 0.2.0'
depends 'chef_task_server', '~> 0.1.0'
depends 'nginx', '~> 2.7.6'
